# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# calls action refreshing the partial

#$(document).on 'turbolinks:load', ->  #  ready page:load
#  REFRESH_INTERVAL_IN_MILLIS = 5000
#  if true #$('.f-pending-message').length > 0
#    setTimeout (->
#      # disable page scrolling to top after loading page content
#      #Turbolinks.enableTransitionCache true
#      # pass current page url to visit method
#      Turbolinks.visit location.toString()
#      # enable page scroll reset in case user clicks other link
#      #Turbolinks.enableTransitionCache false
#      return
#    ), REFRESH_INTERVAL_IN_MILLIS
#  return

# ---
# generated by js2coffee 2.2.0
